export const mockAccounts = [
  {
    id: "1",
    username: "luffy01@gmail.com",
    fullName: "Luffy",
    platform: "facebook",
    profileUrl: "https://facebook.com/",
    avatar: "https://i.pravatar.cc/150?img=1",
    status: "active",
    proxy: "http://127.0.0.1:8001",
    note: "Acc chính, chạy aff",
    lastLogin: new Date("2026-04-08T08:00:00"),
    createdAt: new Date(),
  },
  {
    id: "2",
    username: "zoro02@gmail.com",
    fullName: "Zoro",
    platform: "tiktok",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=2",
    status: "checkpoint",
    proxy: "http://127.0.0.1:8002",
    note: "Dính checkpoint nhẹ",
    lastLogin: new Date("2026-04-07T22:10:00"),
    createdAt: new Date(),
  },
  {
    id: "3",
    username: "nami03@gmail.com",
    fullName: "Nami",
    platform: "instagram",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=3",
    status: "banned",
    proxy: "",
    note: "Acc chết",
    lastLogin: new Date("2026-04-01T10:00:00"),
    createdAt: new Date(),
  },
  {
    id: "4",
    username: "sanji04@gmail.com",
    fullName: "Sanji",
    platform: "facebook",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=4",
    status: "active",
    proxy: "http://127.0.0.1:8004",
    note: "Via mới",
    lastLogin: new Date("2026-04-08T09:30:00"),
    createdAt: new Date(),
  },
  {
    id: "5",
    username: "usopp05@gmail.com",
    fullName: "Usopp",
    platform: "tiktok",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=5",
    status: "active",
    proxy: "",
    note: "Chưa gán proxy",
    lastLogin: new Date("2026-04-06T15:00:00"),
    createdAt: new Date(),
  },
  {
    id: "6",
    username: "robin06@gmail.com",
    fullName: "Robin",
    platform: "instagram",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=6",
    status: "checkpoint",
    proxy: "http://127.0.0.1:8006",
    note: "Login nhiều IP",
    lastLogin: new Date("2026-04-07T18:00:00"),
    createdAt: new Date(),
  },
  {
    id: "7",
    username: "franky07@gmail.com",
    fullName: "Franky",
    platform: "facebook",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=7",
    status: "active",
    proxy: "http://127.0.0.1:8007",
    note: "Acc ads",
    lastLogin: new Date("2026-04-08T07:00:00"),
    createdAt: new Date(),
  },
  {
    id: "8",
    username: "brook08@gmail.com",
    fullName: "Brook",
    platform: "tiktok",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=8",
    status: "banned",
    proxy: "",
    note: "Spam quá tay",
    lastLogin: new Date("2026-03-30T20:00:00"),
    createdAt: new Date(),
  },
  {
    id: "9",
    username: "chopper09@gmail.com",
    fullName: "Chopper",
    platform: "instagram",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=9",
    status: "active",
    proxy: "http://127.0.0.1:8009",
    note: "Nuôi follow",
    lastLogin: new Date("2026-04-08T06:45:00"),
    createdAt: new Date(),
  },
  {
    id: "10",
    username: "ace10@gmail.com",
    fullName: "Ace",
    platform: "facebook",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=10",
    status: "checkpoint",
    proxy: "http://127.0.0.1:8010",
    note: "Checkpoint 72h",
    lastLogin: new Date("2026-04-07T12:00:00"),
    createdAt: new Date(),
  },
  {
    id: "11",
    username: "law11@gmail.com",
    fullName: "Law",
    platform: "tiktok",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=11",
    status: "active",
    proxy: "",
    note: "Test video",
    lastLogin: new Date("2026-04-05T11:00:00"),
    createdAt: new Date(),
  },
  {
    id: "12",
    username: "kid12@gmail.com",
    fullName: "Kid",
    platform: "instagram",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=12",
    status: "active",
    proxy: "http://127.0.0.1:8012",
    note: "Acc phụ",
    lastLogin: new Date("2026-04-08T10:00:00"),
    createdAt: new Date(),
  },
  {
    id: "13",
    username: "shanks13@gmail.com",
    fullName: "Shanks",
    platform: "facebook",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=13",
    status: "banned",
    proxy: "",
    note: "Die acc",
    lastLogin: new Date("2026-03-28T09:00:00"),
    createdAt: new Date(),
  },
  {
    id: "14",
    username: "mihawk14@gmail.com",
    fullName: "Mihawk",
    platform: "tiktok",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=14",
    status: "active",
    proxy: "http://127.0.0.1:8014",
    note: "Acc mạnh",
    lastLogin: new Date("2026-04-08T11:00:00"),
    createdAt: new Date(),
  },
  {
    id: "15",
    username: "dragon15@gmail.com",
    fullName: "Dragon",
    platform: "instagram",
    profileUrl: "",
    avatar: "https://i.pravatar.cc/150?img=15",
    status: "checkpoint",
    proxy: "",
    note: "Login lạ IP",
    lastLogin: new Date("2026-04-07T05:00:00"),
    createdAt: new Date(),
  },
];